- name: set selinux context on certs dir
  sefcontext:
    target: '/etc/dehydrated/certs(/.*)?'
    setype: cert_t
    state: present
  tags:
    - dehydrated

- name: install dehydrated
  package:
    name: dehydrated
    state: latest
  tags:
    - dehydrated

- name: create challenge directory
  file:
    path: /var/www/dehydrated
    state: directory
    setype: _default
  tags:
    - dehydrated

- name: create LE account
  command: dehydrated --register --accept-terms
  args:
    creates: /etc/dehydrated/accounts/*/registration_info.json
  tags:
    - dehydrated

- name: create root SSH keypair for certificate syncing
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_type: rsa
    ssh_key_file: .ssh/id_rsa
    ssh_key_comment: 'root@{{ inventory_hostname }}'
  when: (dehydrated_sync_domains | length) > 0
  tags:
    - dehydrated

- name: configure domains
  template:
    src: dehydrated-domains.txt.j2
    dest: /etc/dehydrated/domains.txt
  notify:
    - run dehydrated
  tags:
    - dehydrated

- name: install hook script
  template:
    src: dehydrated-hook.sh.j2
    dest: /etc/dehydrated/hook.sh
    mode: 0750
  notify:
    - run dehydrated
  tags:
    - dehydrated
