---
# External domain name
buildbot_master_domain: '{{ inventory_hostname }}'

buildbot_master_user: "buildbot-master"
buildbot_master_home: "/srv/buildbot-master"
buildbot_master_db: "buildbot"
buildbot_master_sources_url: "https://sources.flathub.org/sources/"
buildbot_master_sources: "/srv/buildbot-master/sources"
buildbot_master_dir: "{{ buildbot_master_home }}/master"
buildbot_master_sandbox: "{{ buildbot_master_home }}/sandbox"
buildbot_master_version: 2.7.0+flathub1
