---
# External domain name
buildbot_master_domain: buildbot.flathub.org

buildbot_master_user: "buildbot-master"
buildbot_master_home: "/var/lib/private/buildbot-master"
buildbot_master_db: "buildbot"
buildbot_master_sources_url: "https://sources.flathub.org/sources/"
buildbot_master_sources: "/srv/buildbot-master/sources"
buildbot_master_dir: "{{ buildbot_master_home }}/master"
buildbot_master_sandbox: "{{ buildbot_master_home }}/sandbox"
buildbot_master_version: 2.8.4+flathub1
