---
- name: install packages
  package:
    name:
      - ostree
      - flatpak
    state: latest
  tags:
    - repo-manager
    - repo-manager_packages

- name: create user
  user:
    name: "{{ repo_manager_user }}"
    home: "{{ repo_manager_home }}"
    system: yes
  tags:
   - repo-manager

- name: Add postgres user
  postgresql_user:
    name: "{{ repo_manager_user }}"
  become_user: postgres
  tags:
   - repo-manager

- name: Create the database
  postgresql_db:
    name: "{{ repo_manager_db }}"
    owner: "{{ repo_manager_user }}"
  become_user: postgres
  tags:
   - repo-manager

- name: Create bin directory
  file:
    path: "{{ repo_manager_home }}/bin"
    state: directory
    owner: "{{ repo_manager_user }}"
    group: "{{ repo_manager_user }}"
    mode: 0775
  tags:
   - repo-manager

- name: Create gpghome directory
  file:
    path: "{{ repo_manager_gpghome }}"
    state: directory
    owner: "{{ repo_manager_user }}"
    group: "{{ repo_manager_user }}"
    mode: 0700
  tags:
   - repo-manager

- name: Download repo-manager release
  get_url:
    url: "https://github.com/alexlarsson/repo-manager/releases/download/{{ repo_manager_version }}/repo-manager"
    checksum: "{{ repo_manager_checksum }}"
    dest: "{{ repo_manager_home }}/bin/repo-manager"
    mode: 0775
  become_user: "{{ repo_manager_user }}"
  notify:
   - restart repo-manager
  tags:
   - repo-manager

- name: add systemd unit
  template:
    src: repo-manager.service.j2
    dest: /etc/systemd/system/repo-manager.service
  notify:
   - restart repo-manager
  tags:
   - repo-manager

# NOTE: Here you have to put a .env file with the secret and the gpg keys in repo_manager_home the first time

- name: enable and start repo-manager
  systemd:
    name: repo-manager
    daemon_reload: yes
    enabled: yes
  notify:
   - restart repo-manager
  tags:
   - repo-manager
